using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using UnityEngine;
using SimpleFileBrowser;

public class Testing : MonoBehaviour
{

    public string fileToProcess;

    // Start is called before the first frame update
    void Start()
    {
        ProcessStartInfo start = new ProcessStartInfo();

        string progToRun = @"Assets/Scripts/Python/loadNrrd.py";

        fileToProcess = @"C:\Users\Bryce\Brain Visualization\Brain-Visualization\Unity2018_4LTS\Assets\DTIBrain.nrrd";

        int y = 2;

        start.FileName = "C:\\Users\\Bryce\\AppData\\Local\\Programs\\Python\\Python37-32\\python.exe";

        start.Arguments = string.Format("\"{0}\" \"{1}\" \"{2}\"", progToRun, fileToProcess.ToString(), y.ToString());

        start.UseShellExecute = false;// Do not use OS shell

        start.CreateNoWindow = true; // We don't need new window

        start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back

        start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

        using (Process process = Process.Start(start))

        {

            using (StreamReader reader = process.StandardOutput)

            {

                string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script

                string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                UnityEngine.Debug.Log("GOTHERE");
                //result can be parsed to harvest real results
                print(result);
                print(stderr);

            }

        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
